config/routes.rb
AlchemyCrm::Engine.routes.draw do

  match '/recipients/:h/reads' => 'recipients#reads',
    :as => 'recipient_reads'

  match '/recipients/:h/reacts' => 'recipients#reacts',
    :as => 'recipient_reacts'

  match '/subscriptions/:token/destroy/:newsletter_id' => 'subscriptions#destroy',
    :as => 'destroy_subscription'

  match '/admin/elements/teasables' => 'admin/elements#teasables',
    :as => 'teasable_elements'

  match '/admin/elements/teasables' => 'admin/elements#teasables',
    :as => 'teasable_elements'

  match '/contacts/:token/verify' => 'contacts#verify',
    :as => 'verify_contact'

  match '/contacts/:token/disable' => 'contacts#disable',
    :as => 'disable_contact'

  match '/mailings/:m/show/:r' => 'mailings#show',
    :as => 'show_mailing'

  resources :mailings, :only => [:show]

  resources :contacts do
    collection do
      post :signup, :signout
    end
  end

  resources :subscriptions do
    collection do
      post :overview
    end
  end

  namespace :admin do

    resources :contacts do
      collection do
        get :import
        get :autocomplete_tag_list
        post :import
      end
      member { get :export }
    end

    resources :contact_groups do
      collection { get :add_filter }
    end

    resources :newsletters

    resources :deliveries

    resources :mailings do
      resources :deliveries
      collection { get :signout }
      member do
        get :copy
        get :edit_content
      end
    end

  end

end

app/models/alchemy/essence_element_teaser.rb
module Alchemy
  class EssenceElementTeaser < ActiveRecord::Base

    acts_as_essence(
      :ingredient_column => :url,
      :preview_text_method => :url
    )

    # Saves the content from params
    def save_ingredient(params, options = {})
      return true if params.blank?
      self.url = params["url"]
      self.title = params["title"]
      self.text = params["text"]
      self.save!
    end

  end
end

app/helpers/alchemy/pages_helper_extension.rb
Alchemy::PagesHelper.module_eval do

  def render_page_layout(options={})
    default_options = {
      :render_format => "html"
    }
    options = default_options.merge(options)
    if @page.layout_description['newsletter']
      render :partial => "alchemy/newsletter_layouts/#{@page.page_layout.downcase}", :format => options[:render_format]
    else
      render :partial => "alchemy/page_layouts/#{@page.page_layout.downcase}", :format => options[:render_format]
    end
  rescue ActionView::MissingTemplate
    warning("PageLayout: '#{@page.page_layout}' not found. Rendering standard page_layout.")
    render :partial => "alchemy/page_layouts/standard"
  end

end

app/views/alchemy/essences/_essence_date_view.text.erb
<%- if content.essence.date.present? -%>
<%= l(content.essence.date, :format => (options[:date_format])) -%>
<%- end -%>

app/views/alchemy/essences/_essence_element_teaser_editor.html.erb
<div class="content_editor" id="<%= content_dom_id(content) %>">
  <%- if options[:show_link_text] -%>
  <label>Link Text</label>
  <%= text_field_tag(
    "contents[content_#{content.id}][text]",
    content.essence.text,
    :id => "content_#{content.id}_text",
    :class => "thin_border text_long"
  ) %>
  <%- end -%>
  <%= hidden_field_tag "contents[content_#{content.id}][url]", content.essence.url, :id => "content_#{content.id}_url" %>
  <%= hidden_field_tag "contents[content_#{content.id}][title]", content.essence.title, :id => "content_#{content.id}_title" %>
  <div style="overflow: hidden; margin: 4px 0; line-height: 25px">
    <p>
      Mit einem Element aus dem CMS verknüpfen:
      <%= link_to_overlay_window(
        render_icon('fill_from_element'),
        teasable_elements_path(:content_id => content.id),
        {
          :title => 'Element aus dem CMS wählen',
          :size => '450x500'
        },
        {
          :class => 'icon_button',
          :title => 'Element aus dem CMS wählen',
          :style => 'float: right'
        }
      ) -%>
    </p>
  </div>
</div>

app/views/alchemy/essences/_essence_element_teaser_view.html.erb
<a href="<%= recipient_reacts_url(:id => @recipient.id || 1, :host => @server) + content.essence.url if @recipient %>" title="<%= content.essence.title %>"><%= options[:link_text_value] || content.essence.text %></a>

app/views/alchemy/essences/_essence_element_teaser_view.text.erb
<%- if @recipient -%>
<%= recipient_reacts_url(:id => @recipient.id || 1, :host => @server) + content.essence.url %>
<%- end -%>

app/views/alchemy/essences/_essence_richtext_view.text.erb
<%= content.essence.stripped_body %>

app/views/alchemy/essences/_essence_text_view.text.erb
<%= content.essence.body %>