config/routes.rb
AlchemyCrm::Engine.routes.draw do

  match '/recipients/:h/reads' => 'recipients#reads',
    :as => 'recipient_reads'

  match '/recipients/:h/reacts' => 'recipients#reacts',
    :as => 'recipient_reacts'

  match '/subscriptions/:token/destroy/:newsletter_id' => 'subscriptions#destroy',
    :as => 'destroy_subscription'

  match '/admin/elements/teasables' => 'admin/elements#teasables',
    :as => 'teasable_elements'

  match '/admin/elements/teasables' => 'admin/elements#teasables',
    :as => 'teasable_elements'

  match '/contacts/:token/verify' => 'contacts#verify',
    :as => 'verify_contact'

  match '/contacts/:token/disable' => 'contacts#disable',
    :as => 'disable_contact'

  match '/mailings/:m/show/:r' => 'mailings#show',
    :as => 'show_mailing'

  resources :mailings, :only => [:show]

  resources :contacts do
    collection do
      post :signup, :signout
    end
  end

  resources :subscriptions do
    collection do
      post :overview
    end
  end

  namespace :admin do

    resources :contacts do
      collection do
        get :import
        get :autocomplete_tag_list
        post :import
      end
      member { get :export }
    end

    resources :contact_groups do
      collection { get :add_filter }
    end

    resources :newsletters

    resources :deliveries

    resources :mailings do
      resources :deliveries
      collection { get :signout }
      member do
        get :copy
        get :edit_content
      end
    end

  end

end

app/models/alchemy_crm/contact.rb
# encoding: UTF-8

module AlchemyCrm
  class Contact < ActiveRecord::Base

    acts_as_taggable

    attr_accessible(
      :salutation,
      :title,
      :firstname,
      :lastname,
      :email,
      :phone,
      :mobile,
      :address,
      :zip,
      :city,
      :company,
      :country,
      :subscriptions_attributes,
      :verified,
      :disabled,
      :tag_list
    )

    has_many :subscriptions, :dependent => :destroy
    has_many :newsletters, :through => :subscriptions, :uniq => true
    has_many :recipients

    accepts_nested_attributes_for :subscriptions, :allow_destroy => true

    Config.get(:additional_contact_validations).each do |field|
      validates_presence_of field.to_sym
    end
    validates_presence_of :email
    validates_uniqueness_of :email, :if => proc { email.present? }
    validates_format_of :email, :with => ::Devise.email_regexp, :if => proc { errors[:email].blank? }

    before_save :update_sha1, :if => proc { email_sha1.blank? || email_changed? }

    scope :verified, where(:verified => true)
    scope :disabled, where(:disabled => true)
    scope :enabled, where(:disabled => false)
    scope :available, verified.enabled

    COLUMN_NAMES = [
      [::I18n.t(:title, :scope => 'activerecord.attributes.alchemy_crm/contact', :default => 'Title'), "title"],
      [::I18n.t(:salutation, :scope => 'activerecord.attributes.alchemy_crm/contact', :default => 'Salutation'), "salutation"],
      [::I18n.t(:firstname, :scope => 'activerecord.attributes.alchemy_crm/contact', :default => 'Firstname'), "firstname"],
      [::I18n.t(:lastname, :scope => 'activerecord.attributes.alchemy_crm/contact', :default => 'Lastname'), "lastname"],
      [::I18n.t(:address, :scope => 'activerecord.attributes.alchemy_crm/contact', :default => 'Address'), "address"],
      [::I18n.t(:zip, :scope => 'activerecord.attributes.alchemy_crm/contact', :default => 'Zipcode'), "zip"],
      [::I18n.t(:city, :scope => 'activerecord.attributes.alchemy_crm/contact', :default => 'City'), "city"],
      [::I18n.t(:country, :scope => 'activerecord.attributes.alchemy_crm/contact', :default => 'Country'), "country"],
      [::I18n.t(:company, :scope => 'activerecord.attributes.alchemy_crm/contact', :default => 'Company'), "company"]
    ]

    INTERPOLATION_NAME_METHODS = %w(fullname name_with_title firstname lastname name email)

    def disable!
      update_attributes({
        :verified => false,
        :disabled => true
      })
      subscriptions.destroy_all
    end

    # Returns a full name
    # Salutation + Title + Firstname + Lastname
    def fullname
      if lastname.present? || firstname.present?
        "#{translated_salutation} #{name_with_title}".squeeze(" ")
      else
        name
      end
    end

    # Translated salutation
    #
    # Translate the saluations in your +config/LOCALE.yml+
    #
    #   alchemy_crm:
    #     salutations:
    #       mr:
    #       ms:
    #
    def translated_salutation
      ::I18n.t(salutation, :scope => [:alchemy_crm, :salutations], :default => salutation.to_s.capitalize)
    end

    # Returns the name and title
    # Title + Firstname + Lastname
    def name_with_title
      "#{title} #{name}".squeeze(" ")
    end

    # Returns the name ot email, if no name is present
    # Firstname + Lastname, or email
    def name
      if lastname.present? || firstname.present?
        "#{firstname} #{lastname}".squeeze(" ")
      else
        email
      end
    end

    # Uses the +config['name_interpolation_method']+ to return the value for emails and forms %{name} interpolations.
    def interpolation_name_value
      name_interpolation_method = Config.get(:name_interpolation_method)
      if name_interpolation_method.present? && INTERPOLATION_NAME_METHODS.include?(name_interpolation_method.to_s) && self.respond_to?(name_interpolation_method.to_sym)
        self.send(name_interpolation_method.to_sym)
      else
        fullname
      end
    end

    def self.fake
      fake = new(
        :salutation => nil,
        :title => ::I18n.t(:title, :scope => 'alchemy_crm.fake_contact_attributes', :default => 'Dr.'),
        :firstname => ::I18n.t(:firstname, :scope => 'alchemy_crm.fake_contact_attributes', :default => 'Jon'),
        :lastname => ::I18n.t(:lastname, :scope => 'alchemy_crm.fake_contact_attributes', :default => 'Doe'),
        :email => ::I18n.t(:email, :scope => 'alchemy_crm.fake_contact_attributes', :default => 'jon@doe.com'),
        :phone => ::I18n.t(:phone, :scope => 'alchemy_crm.fake_contact_attributes', :default => '1-1234567'),
        :mobile => ::I18n.t(:mobile, :scope => 'alchemy_crm.fake_contact_attributes', :default => '123-456789'),
        :address => ::I18n.t(:address, :scope => 'alchemy_crm.fake_contact_attributes', :default => 'Street 1'),
        :zip => ::I18n.t(:zip, :scope => 'alchemy_crm.fake_contact_attributes', :default => '10000'),
        :city => ::I18n.t(:city, :scope => 'alchemy_crm.fake_contact_attributes', :default => 'City'),
        :company => ::I18n.t(:company, :scope => 'alchemy_crm.fake_contact_attributes', :default => 'Company inc.'),
        :country => ::I18n.t(:country, :scope => 'alchemy_crm.fake_contact_attributes', :default => 'US')
      )
      fake.readonly!
      fake
    end

    def self.replace_tag(old_tag, new_tag)
      self.tagged_with(old_tag).each do |contact|
        contact.tags.delete(old_tag)
        contact.tags << new_tag
        contact.save
      end
    end

    def self.find_by_query(query, options, paginate)
      column_names = Contact.public_column_names
      search_string = (column_names.join(" LIKE '%#{query}%' OR ") + " LIKE '%#{query}%'")
      contacts = where(search_string)
      if paginate
        contacts.paginate(options)
      else
        contacts
      end
    end

    #TODO: Zu den selbstgewählten Mailingformaten müssten noch alle durch den Backend User gewählten Formate mit angezeigt werden, oder?
    def all_newsletters
      self.newsletters
    end

    def self.public_column_names
      Contact.column_names - ["created_at", "updated_at", "email_salt", "verified", "email_sha1", "id"]
    end

    def self.filterable_column_names
      COLUMN_NAMES
    end

    def self.find_or_create(data)
      if (contact = Contact.find_by_email(data[:email])).nil?
        contact = Contact.create(data)
      end
      contact
    end

    def all_subscriptions_verified?
      self.subscriptions.inject(true){|acc, s| acc = s.verified? && acc; acc}
    end

    def self.clean_human_attribute_name(attrb)
      human_attribute_name(attrb).gsub(/\*$/, '')
    end

    def self.new_from_recipient(recipient)
      raise "No recipient found!" if recipient.nil?
      contact = new(:email => recipient.email, :lastname => recipient.email)
      contact.readonly!
      contact
    end

    def self.new_from_vcard(vcard, verified)
      raise "No vcard found!" if vcard.nil?
      raise ::I18n.t(:imported_contacts_not_verified, :scope => :alchemy_crm) if !verified
      contacts = []
      ::Vpim::Vcard.decode(vcard).each do |card|
        remapped_attributes = {
          :company => card.org.blank? ? nil : card.org.first,
          :lastname => card.name.blank? ? nil : card.name.family,
          :firstname => card.name.blank? ? nil : card.name.given,
          :title => card.name.blank? ? nil : card.name.prefix,
          :address => card.address.blank? ? nil : card.address.street,
          :city => card.address.blank? ? nil : card.address.locality,
          :country => card.address.blank? ? nil : card.address.country,
          :zip => card.address.blank? ? nil : card.address.postalcode,
          :email => card.email.to_s,
          :phone => card.telephone ? card.telephone.location.include?("cell") ? nil : card.telephone.to_s : nil,
          :mobile => card.telephones.detect { |t| t.location.include?("cell") }.to_s,
          :verified => true
        }
        contacts << Contact.create(remapped_attributes)
      end
      contacts
    end

    def to_vcard
      card = Vpim::Vcard::Maker.make2 do |maker|
        maker.add_name do |name|
          name.prefix = title unless title.blank?
          name.given = firstname unless firstname.blank?
          name.family = lastname unless lastname.blank?
        end
        maker.add_tel(phone) { |t| t.location = 'work' } unless phone.blank?
        maker.add_tel(mobile) { |t| t.location = 'cell' } unless mobile.blank?
        maker.add_email(email) { |e| e.location = 'work' } unless email.blank?
        maker.add_addr do |addr|
          addr.street = address
          addr.postalcode = zip
          addr.locality = city
          addr.country = country
        end
        maker.org = company
      end
      vcf = File.new(Rails.root.to_s + "/tmp/#{fullname}.vcf", "w")
      vcf.write(card.encode)
      vcf.close
    end

  private

    def update_sha1
      salt = email_salt || [Array.new(6){rand(256).chr}.join].pack("m")[0..7]
      self.email_salt, self.email_sha1 = salt, Digest::SHA1.hexdigest(email + salt)
    end

  end
end

app/controllers/alchemy_crm/admin/contacts_controller.rb
# encoding: UTF-8
module AlchemyCrm
  module Admin
    class ContactsController < AlchemyCrm::Admin::BaseController

      include CSVMagic::ControllerActions

      csv_magic_config(
        :mapping => {
          Contact.clean_human_attribute_name(:salutation)  => :salutation,
          Contact.clean_human_attribute_name(:title)       => :title,
          Contact.clean_human_attribute_name(:firstname)   => :firstname,
          Contact.clean_human_attribute_name(:lastname)    => :lastname,
          Contact.clean_human_attribute_name(:email)       => :email,
          Contact.clean_human_attribute_name(:company)     => :company,
          Contact.clean_human_attribute_name(:address)     => :address,
          Contact.clean_human_attribute_name(:zip)         => :zip,
          Contact.clean_human_attribute_name(:city)        => :city,
          Contact.clean_human_attribute_name(:country)     => :country,
          Contact.clean_human_attribute_name(:phone)       => :phone,
          Contact.clean_human_attribute_name(:mobile)      => :mobile,
          Contact.human_attribute_name(:tag_list)          => :tag_list
        }
      )

      before_filter :load_tags, :only => [:new, :edit]

      def new
        @contact = Contact.new(:country => ::I18n.locale.to_s.upcase)
        render :layout => false
      end

      def import
        if request.post?
          if params[:verified] == "1"
            if params[:fields] || (params[:file] && !is_vcard_file?(params[:file]))
              handle_csv_post_request
            else
              handle_vcf_post_request
            end
          else
            @error = build_error_message(alchemy_crm_t(:imported_contacts_not_verified))
          end
        else
          render :layout => !request.xhr?
        end
      end

      def export
        @contact = Contact.find(params[:id])
        @contact.to_vcard
        send_file("#{Rails.root.to_s}/tmp/#{@contact.fullname}.vcf")
      end

      def autocomplete_tag_list
        items = ActsAsTaggableOn::Tag.where(['LOWER(name) LIKE ?', "#{params[:term].downcase}%"])
        render :json => json_for_autocomplete(items, :name)
      end

    private

      def load_tags
        @tags = ActsAsTaggableOn::Tag.order("name ASC").all
        @tags = @tags - @contact.tags.to_a unless @contact.nil?
      end

      def build_error_message(message)
        heading = "<h1>#{alchemy_crm_t(:errors_while_importing)}</h1>".html_safe
        message = "<p>#{message}</p>".html_safe
        heading + message
      end

      def create_resource_items_from_csv(*args)
        @csv_import_errors = []
        @contacts = []
        reader = CSVMagic::Reader.new(params)
        reader.each do |row|
          @contacts << contact = Contact.new(row)
          contact.verified = true
          unless contact.save
            @csv_import_errors.push [contact, contact.errors]
          end
        end
        @valid_contacts = @contacts.select(&:valid?)
        reader.remove_file if @csv_import_errors.empty?
      end

      def render_csv_import_form
        render 'import'
      end

      def handle_vcf_post_request
        if params[:file].blank?
          @errors = build_error_message(alchemy_crm_t(:missing_vcard))
        else
          @contacts = Contact.new_from_vcard(params[:file], true)
          if @contacts.empty?
            flash[:error] = alchemy_crm_t(:no_contacts_imported)
          elsif @contacts.detect(&:invalid?).nil?
            flash[:notice] = alchemy_crm_t(:successfully_imported_contacts)
          else
            @errors = build_error_message(alchemy_crm_t(:please_check_highlighted_vcards_on_errors))
          end
        end
        @valid_contacts = @contacts.select(&:valid?) || []
        render :vcf_import_result
      end

      def is_vcard_file?(file)
        content = file.read
        file.rewind
        content.starts_with?("BEGIN:VCARD")
      end

    end
  end
end

app/controllers/alchemy_crm/contacts_controller.rb
# encoding: UTF-8
module AlchemyCrm
  class ContactsController < AlchemyCrm::BaseController

    helper 'Alchemy::Pages'
    layout :layout_for_page

    before_filter :load_signup_form, :only => [:show, :signup, :verify]
    before_filter :load_signout_form, :only => [:signout, :disable]

    def show
      @page = @element.page
      @root_page = @page.get_language_root
      render :template => 'alchemy/pages/show'
    end

    def signup
      @contact = Contact.new(params[:contact])
      if @contact.save
        ContactsMailer.signup_mail(
          @contact,
          Alchemy::Page.find_by_page_layout_and_language_id('newsletter_mails', session[:language_id])
        ).deliver
        @contact_signed_up = true
      else
        @contact_signed_up = false
      end
      @page = @element.page
      @root_page = @page.get_language_root
      render :template => 'alchemy/pages/show'
    end

    def verify
      @contact = Contact.find_by_email_sha1(params[:token])
      if @contact
        @contact_verified = @contact.update_attribute(:verified, true)
        if params[:newsletter_ids]
          @subscriptions = @contact.subscriptions.where(:newsletter_id => params[:newsletter_ids])
        else
          @subscriptions = @contact.subscriptions
        end
        @subscriptions.each do |subscription|
          subscription.update_attribute(:verified, true)
        end
        @page = @element.page
        @root_page = @page.get_language_root
        render :template => 'alchemy/pages/show'
      else
        contact_not_found
      end
    end

    def signout
      @contact = Contact.find_by_email_and_verified(params[:email], true)
      if @contact.blank?
        flash[:notice] = ::I18n.t(:contact_unknown, :scope => :alchemy_crm)
        @contact_signed_out = false
      else
        ContactsMailer.signout_mail(
          @contact,
          Alchemy::Page.find_by_page_layout_and_language_id('newsletter_mails', session[:language_id])
        ).deliver
        @contact_signed_out = true
      end
      @page = @element.page
      @root_page = @page.get_language_root
      render :template => 'alchemy/pages/show'
    end

    def disable
      @contact = Contact.find_by_email_sha1(params[:token])
      if @contact
        @contact_disabled = @contact.disable!
        @page = @element.page
        @root_page = @page.get_language_root
        render :template => 'alchemy/pages/show'
      else
        contact_not_found
      end
    end

  private

    def load_signup_form
      @element = Alchemy::Element.find_by_name('newsletter_signup_form')
      if @element.blank?
        raise ActiveRecord::RecordNotFound, "Alchemy::Element with name 'newsletter_signup_form' not found!"
      end
    end

    def load_signout_form
      @element = Alchemy::Element.find_by_name('newsletter_signout_form')
      if @element.blank?
        raise ActiveRecord::RecordNotFound, "Alchemy::Element with name 'newsletter_signout_form' not found!"
      end
    end

    def contact_not_found
      raise ActionController::RoutingError.new('Contact Not Found')
    end

  end
end

app/views/alchemy_crm/admin/contacts/_contact.html.erb
<tr class="<%= cycle('even', 'odd') %><%= contact.disabled? ? ' disabled' : nil %>">
  <td class="icon">
    <%= content_tag('span', '', :class => 'icon contact') %>
  </td>
  <td class="name" style="width: 180px">
    <%= contact.lastname %>
  </td>
  <td class="name" style="width: 180px">
    <%= contact.firstname %>
  </td>
  <td class="name"><%= contact.company %></td>
  <td class="email"><%= contact.email %></td>
  <td class="tags"><%= contact.tag_list %></td>
  <td class="center"><%= render_icon contact.verified? && !contact.disabled %></td>
  <td class="tools">
    <%= link_to_overlay_window(
      '',
      edit_admin_contact_path(contact),
      {
        :title => alchemy_crm_t(:edit_contact),
        :size => '415x560'
      },
      {
        :title => alchemy_crm_t(:edit_contact),
        :class => 'icon contact_edit'
      }
    ) -%>
    <%= link_to(
      '',
      export_admin_contact_path(contact),
      {
        :title => alchemy_crm_t(:export_contact),
        :class => 'icon contact_export'
      }
    ) -%>
    <%= link_to_confirmation_window(
      "",
      alchemy_crm_t(:do_you_really_want_to_delete_this_contact?),
      admin_contact_path(contact),
      :title => alchemy_crm_t(:delete_contact),
      :class => 'icon contact_delete'
    ) %>
  </td>
</tr>

app/views/alchemy_crm/admin/contacts/_form.html.erb
<%= form_for [:admin, @contact], :remote => true do |f| %>
<div id="errors" style="display:none"></div>
<% if @contact.disabled? -%>
<div class="info">
  <%= render_icon(:info) %>
  <p>
    <strong><%= alchemy_crm_t(:contact_is_disabled_notice) %></strong>
  </p>
</div>
<% end -%>
<table id="contact">
  <tr>
    <td class="label"><%= f.label :salutation %></td>
    <td class="select">
      <%= f.select(:salutation,
        options_for_select([
          [t('Please choose'), ''],
          [alchemy_crm_t(:mr, :scope => 'salutations'), :mr],
          [alchemy_crm_t(:ms, :scope => 'salutations'), :ms]
        ], @contact.salutation), {}, { :class => 'alchemy_selectbox very_short' }) %>
    </td>
    <td class="label right"><%= f.label :title %></td>
    <td class="input"><%= f.text_field :title, :class => "thin_border medium_long" %></td>
  </tr>
  <tr>
    <td class="label"><%= f.label :firstname %></td>
    <td colspan="3" class="input"><%= f.text_field :firstname, :class => "thin_border very_long" %></td>
  </tr>
  <tr>
    <td class="label"><%= f.label :lastname %></td>
    <td colspan="3" class="input"><%= f.text_field :lastname, :class => "thin_border very_long" %></td>
  </tr>
  <tr>
    <td class="label"><%= f.label :company %></td>
    <td colspan="3" class="input"><%= f.text_field :company, :class => "thin_border very_long" %></td>
  </tr>
  <tr>
    <td class="label"><%= f.label :email %></td>
    <td colspan="3" class="input"><%= f.text_field :email, :class => "thin_border very_long" %></td>
  </tr>
  <tr>
    <td class="label"><%= f.label :phone %></td>
    <td colspan="3" class="input"><%= f.text_field :phone, :class => "thin_border very_long" %></td>
  </tr>
  <tr>
    <td class="label"><%= f.label :mobile %></td>
    <td colspan="3" class="input"><%= f.text_field :mobile, :class => "thin_border very_long" %></td>
  </tr>
  <tr>
    <td class="label"><%= f.label :address %></td>
    <td colspan="3" class="input"><%= f.text_field :address, :class => "thin_border very_long" %></td>
  </tr>
  <tr>
    <td class="label"><%= f.label :zip %></td>
    <td class="input"><%= f.text_field :zip, :class => "thin_border short" %></td>
    <td class="label right"><%= f.label :city %></td>
    <td class="input"><%= f.text_field :city, :class => "thin_border medium_long" %></td>
  </tr>
  <tr>
    <td class="label"><%= f.label :country %></td>
    <td colspan="3" class="input">
      <%= f.country_select :country, {}, {:include_blank => t('Please choose')}, {:class => "alchemy_selectbox very_long"} %>
    </td>
  </tr>
  <tr>
    <td class="label"><%= f.label :tag_list %></td>
    <td colspan="3" class="input">
      <%= f.autocomplete_field :tag_list, autocomplete_tag_list_admin_contacts_path, :class => "thin_border very_long", 'data-delimiter' => ',' %>
      <p><small>*<%= alchemy_crm_t(:seperate_tags_with_comma) %></small></p>
    </td>
  </tr>
  <tr>
    <td class="label">Status</td>
    <td class="checkbox" colspan="3">
      <%= f.check_box :verified %>
      <%= f.label :verified %>
      <%= f.check_box :disabled %>
      <%= f.label :disabled %>
    </td>
  </tr>
  <tr>
    <td class="submit" colspan="4"><%= f.button t(:save), :class => "button" %></td>
  </tr>
</table>

<% end %>

app/views/alchemy_crm/admin/contacts/edit.html.erb
<%= render :partial => "form" %>

app/views/alchemy_crm/admin/contacts/import.html.erb
<%= form_tag import_admin_contacts_path, :remote => request.xhr?, :multipart => true, :class => 'contact_import' do %>

  <div class="info">
    <%= render_icon('info') %>
    <h1><%= alchemy_crm_t(:headline, :scope => 'import_format_notice') %></h1>
    <ul>
      <li><%= alchemy_crm_t(:vcf_format, :scope => 'import_format_notice') %></li>
      <li><%= alchemy_crm_t(:csv_format, :scope => 'import_format_notice') %></li>
    </ul>
  </div>

  <div id="errors" style="display: none"></div>

  <table>
    <tr>
      <td class="label"><%= label_tag :file, alchemy_crm_t(:file) %></td>
      <td><%= file_field_tag :file %></td>
    </tr>
    <tr>
      <td></td>
      <td>
        <%= check_box_tag :verified %>
        <%= label_tag :verified, alchemy_crm_t(:import_contacts_verified) %>
      </td>
    </tr>
    <tr>
      <td class="submit" colspan="2">
        <%= button_tag alchemy_crm_t(:import), :name => nil, :class => 'button' %>
      </td>
    </tr>
  </table>

<% end %>

app/views/alchemy_crm/admin/contacts/import.js.erb
$('div#errors').html('<%= @error -%>').show();
Alchemy.enableButton('button.button');

app/views/alchemy_crm/admin/contacts/index.html.erb
<% content_for(:javascript_includes) do -%>
  <%= javascript_include_tag "alchemy_crm/scripts.js" %>
<% end -%>

<% content_for(:stylesheets) do -%>
  <%= stylesheet_link_tag('alchemy_crm/styles') %>
<% end -%>

<% toolbar(
  :buttons => [
    {
      :icon => "contact_add",
      :label => alchemy_crm_t(:add_contact),
      :url => alchemy_crm.new_admin_contact_path,
      :title => alchemy_crm_t(:add_contact),
      :overlay_options => {
        :title => alchemy_crm_t(:add_contact),
        :size => '415x560'
      },
      :if_permitted_to => [:new, :alchemy_crm_admin_contacts]
    },
    {
      :icon => :contact_import,
      :label => alchemy_crm_t(:import_contacts),
      :url => alchemy_crm.import_admin_contacts_path,
      :title => alchemy_crm_t(:import_contacts),
      :overlay_options => {
        :title => alchemy_crm_t(:import_contacts),
        :size => '400x300'
      },
      :if_permitted_to => [:import, :alchemy_crm_admin_contacts]
    }
  ]
) %>

<table class="list">
  <%- unless @contacts.blank? -%>
  <tr>
    <th class="icon"></th>
    <th class="name" style="width: 180px"><%= translate_model_attribute(:contact, :lastname).gsub(/\*$/, '') %></th>
    <th class="name" style="width: 180px"><%= translate_model_attribute(:contact, :firstname).gsub(/\*$/, '') %></th>
    <th class="name"><%= translate_model_attribute(:contact, :company) %></th>
    <th class="name"><%= translate_model_attribute(:contact, :email).gsub(/\*$/, '') %></th>
    <th class="name"><%= translate_model_attribute(:contact, :tags) %></th>
    <th class="center"><%= translate_model_attribute(:contact, :verified) %></th>
    <th class="tools" style="width: 60px"></th>
  </tr>
  <%- end -%>
  <%= render :partial => "alchemy_crm/admin/contacts/contact", :collection => @contacts %>
</table>
<%= render 'alchemy/admin/partials/pagination_links', :items => @contacts, :scope => alchemy_crm %>

app/views/alchemy_crm/admin/contacts/new.html.erb
<%= render :partial => "form" %>

app/views/alchemy_crm/admin/contacts/vcf_import_result.html.erb
<%- content_for(:javascript_includes) do -%>
  <%= javascript_include_tag "alchemy_crm/scripts.js" %>
<%- end -%>

<%- content_for(:stylesheets) do -%>
  <%= stylesheet_link_tag('alchemy_crm/styles') %>
<%- end -%>

<h1><%= alchemy_crm_t('Import result') %></h1>

<% if @valid_contacts.any? -%>
<div class="flash notice" style="margin: 8px 0">
  <%= render_icon('true') %>
  <%= alchemy_crm_t('%{count} contacts imported successfully') % {:count => @valid_contacts.length} %>
</div>
<% end -%>

<% if @errors -%>
<div class="flash error" style="margin: 8px 0">
  <%= render_icon('error') %><%= @errors %>
</div>
<% end -%>

<% if @contacts.any? -%>
<table>
  <tr>
    <th><%= translate_model_attribute(:contact, :name) %></th>
    <th><%= translate_model_attribute(:contact, :email).gsub(/\*$/, '') %></th>
    <th><%= alchemy_crm_t(:import_status) %></th>
  </tr>
  <% @contacts.each do |contact| -%>
  <tr class="<%= cycle("even", "odd") %><%= contact.invalid? ? ' disabled' : nil -%>">
    <td><%= contact.fullname %></td>
    <td><%= contact.email %></td>
    <td>
      <% if contact.valid? -%>
      <%= render_icon(:true) %>
      <% else -%>
      <%= contact.errors.full_messages.join('<br>') %>
      <% end -%>
    </td>
  </tr>
  <% end -%>
</table>
<% else -%>
<p><%= alchemy_crm_t(:no_contacts_imported) %></p>
<% end -%>

<p style="margin: 8px 0; height: 25px">
  <%= link_to t(:continue), admin_contacts_path, :class => 'button' %>
</p>